### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by zivzmy** [xmxoxo/BERT-train2deploy#18]
(tf) yang@yang-Precision-Tower-7810:~/桌面/BERT-train2deploy-master$ cd /home/yang/桌面/BERT-train2deploy-master
(tf) yang@yang-Precision-Tower-7810:~/桌面/BERT-train2deploy-master$ export BERT_BASE_DIR=/home/yang/桌面/BERT-train2deploy-master/chinese_L-12_H-768_A-12
(tf) yang@yang-Precision-Tower-7810:~/桌面/BERT-train2deploy-master$ export GLUE_DIR=/home/yang/桌面/BERT-train2deploy-master/data
(tf) yang@yang-Precision-Tower-7810:~/桌面/BERT-train2deploy-master$ export TRAINED_CLASSIFIER=/home/yang/桌面/BERT-train2deploy-master/output
(tf) yang@yang-Precision-Tower-7810:~/桌面/BERT-train2deploy-master$ export EXP_NAME=mobile_0
(tf) yang@yang-Precision-Tower-7810:~/桌面/BERT-train2deploy-master$ 
(tf) yang@yang-Precision-Tower-7810:~/桌面/BERT-train2deploy-master$ sudo python run_mobile.py \
>   --task_name=setiment \
>   --do_train=true \
>   --do_eval=true \
>   --data_dir=$GLUE_DIR/$EXP_NAME \
>   --vocab_file=$BERT_BASE_DIR/vocab.txt \
>   --bert_config_file=$BERT_BASE_DIR/bert_config.json \
>   --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
>   --max_seq_length=128 \
>   --train_batch_size=32 \
>   --learning_rate=2e-5 \
>   --num_train_epochs=5.0 \
>   --output_dir=$TRAINED_CLASSIFIER/$EXP_NAME
[sudo] yang 的密码： 
Traceback (most recent call last):
  File "run_mobile.py", line 24, in <module>
    import modeling
  File "/home/yang/桌面/BERT-train2deploy-master/modeling.py", line 26, in <module>
    import six
ImportError: No module named six
我在pycharm的terminal中运行，按照楼主的步骤走的，six已经装好啦，还是报错。是怎么回事呢？麻烦大神解答下

**Comment by zivzmy** [comment]
/home/yang/anaconda3/envs/tf/bin/python3.7 /home/yang/桌面/BERT-train2deploy-master/run_mobile.py
Traceback (most recent call last):
  File "/home/yang/桌面/BERT-train2deploy-master/run_mobile.py", line 25, in <module>
    import optimization
  File "/home/yang/桌面/BERT-train2deploy-master/optimization.py", line 87, in <module>
    class AdamWeightDecayOptimizer(tf.train.Optimizer):
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'
我单独运行了下run_mobile.py，报的错误
